name: GitHub Actions Demo
on:
  push:
    paths-ignore:
      - .github/**
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "15 6 * * 0"
  workflow_dispatch: {}
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Show repo info
        run: |-
          echo "Event: ${{ github.event_name }}"
          echo "Branch name: ${{ github.ref }}"
      - uses: actions/checkout@v3.3.0
      - name: List files in the repository
        run: ls -la
